version: '3.8'

services:
  authorization:
    build:
      context: ./
      dockerfile: ./cmd/auth/Dockerfile
    command: ./wait-for-postgres.sh db_umlaut ./auth
    restart: always
    depends_on:
      - db_umlaut
      - redis
      - db_admin
    ports:
      - "8001:8001"
    environment:
      - DB_PASSWORD=1474

  feed:
    build:
      context: ./
      dockerfile: ./cmd/feed/Dockerfile
    command: ./wait-for-postgres.sh db_umlaut ./feed
    restart: always
    depends_on:
      - db_umlaut
      - redis
    ports:
      - "8002:8002"
    environment:
      - DB_PASSWORD=1474

  admin:
    build:
      context: ./
      dockerfile: ./cmd/admin/Dockerfile
    command: ./wait-for-postgres.sh db_admin ./admin
    restart: always
    depends_on:
      - db_admin
    ports:
      - "8003:8003"
    environment:
      - DB_PASSWORD=1474

  umlaut:
    build:
      context: ./
      dockerfile: ./cmd/app/Dockerfile
    command: ./wait-for-postgres.sh db_umlaut ./umlaut
    ports:
      - 8000:8000
    depends_on:
      - db_umlaut
      - redis
      - minio
      - authorization
    environment:
      - DB_PASSWORD=1474

  db_umlaut:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./db/umlaut/migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=1474
    ports:
      - 5432:5432

  db_admin:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
      - ./db/admin/migrations/000001_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=1474
    ports:
      - 5434:5434

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  minio:
    image: minio/minio:latest
    command: server /data --address ":9000" --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: umlaut
      MINIO_ROOT_PASSWORD: minio123
      MINIO_HTTP_TRACE: /tmp/minio.log
    volumes:
      - ./.database/minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  
  nginx:
    image: nginx:latest
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    restart: unless-stopped
    tty: true
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/umlaut-bmstu.me/fullchain.pem:/etc/keys/umlaut-bmstu.me/fullchain.pem
      - /etc/letsencrypt/live/umlaut-bmstu.me/privkey.pem:/etc/keys/umlaut-bmstu.me/privkey.pem
      - /home/ubuntu/front/2023_2_Umlaut/dist:/var/www/html
    ports:
      - 80:80
      - 443:443
    depends_on:
      - umlaut
