global:
  scrape_interval: 30s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "server"
    scrape_interval: 10s
    static_configs:
      - targets: [ umlaut:8000 ]
  - job_name: "authorization"
    scrape_interval: 10s
    static_configs:
      - targets: [ authorization:9091 ]
  - job_name: "feed"
    scrape_interval: 10s
    static_configs:
      - targets: [ feed:9092 ]
  - job_name: "admin"
    scrape_interval: 10s
    static_configs:
      - targets: [ admin:9093 ]
  - job_name: "node exporter"
    scrape_interval: 15s
    static_configs:
      - targets: [ "node-exporter:9100" ]