port: "8000"

postgres:
  username: "postgres"
  host: "db"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

redis:
  addr: "redis:6379"
  db: "0"

cors:
  origins: [
    "http://localhost:8000"
  ]
  methods: [
    "GET",
    "POST",
    "PUT",
    "DELETE",
    "HEAD",
    "OPTIONS"
  ]
