basePath: /
definitions:
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  handler.signInInput:
    properties:
      mail:
        type: string
      password:
        type: string
    required:
    - mail
    - password
    type: object
  model.User:
    properties:
      age:
        type: integer
      description:
        type: string
      education:
        type: string
      hobbies:
        type: string
      looking:
        type: string
      mail:
        type: string
      name:
        type: string
      password:
        type: string
      prefer_gender:
        type: string
      tags:
        type: string
      user_gender:
        type: string
    required:
    - mail
    - name
    - password
    type: object
host: localhost:8000
info:
  contact: {}
  description: API Server for Umlaut Application
  title: Umlaut API
  version: "1.0"
paths:
  /api/feed:
    get:
      consumes:
      - application/json
      description: Next user for feed
      operationId: feed
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: feed
      tags:
      - feed
  /auth/login:
    post:
      consumes:
      - application/json
      description: login
      operationId: login
      parameters:
      - description: Sign-in input parameters
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.signInInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: signIn
      tags:
      - auth
  /auth/logout:
    get:
      consumes:
      - application/json
      description: logout
      operationId: logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: logout
      tags:
      - auth
  /auth/sign-up:
    post:
      consumes:
      - application/json
      description: create account
      operationId: create-account
      parameters:
      - description: Sign-up input user
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: signUp
      tags:
      - auth
swagger: "2.0"
