name: CD

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - closed

jobs:
  deploy:
    name: Backend deploy
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd 2023_2_Umlaut/
            git pull
      - name: Pull docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd 2023_2_Umlaut/
            sudo docker compose -f docker-compose-cd.yml pull
      - name: Run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd 2023_2_Umlaut/
            sudo docker compose -f docker-compose-cd.yml up --renew-anon-volumes --build -d
      - name: Clear old images and containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd 2023_2_Umlaut/
            sudo docker system prune
            y