name: CD

on:
  pull_request:
    branches:
      - main
      - dev
    types:
      - closed

jobs:
  build:
    name: Run Build
    #    needs: [ linter, tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Shutdown process
        run: make down
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push authorization
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/auth/Dockerfile
          platforms: linux/amd64
          push: true
          tags: 100ma/umlaut-auth:latest
      - name: Build and push feed
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/feed/Dockerfile
          platforms: linux/amd64
          push: true
          tags: 100ma/umlaut-feed:latest
      - name: Build and push admin
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/admin/Dockerfile
          platforms: linux/amd64
          push: true
          tags: 100ma/umlaut-admin:latest
      - name: Build and push app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/app/Dockerfile
          platforms: linux/amd64
          push: true
          tags: 100ma/umlaut-app:latest

  deploy:
    name: Backend deploy
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd 2023_2_Umlaut/
            git pull
      - name: Pull docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd 2023_2_Umlaut/
            sudo docker compose -f docker-compose-cd.yml pull
      - name: Run docker-compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd 2023_2_Umlaut/
            sudo docker compose -f docker-compose-cd.yml up --renew-anon-volumes --build -d
      - name: Clear old images and containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd 2023_2_Umlaut/
            sudo docker system prune
            y