name: CI

on:
  push:
    branches-ignore:
      - '*'

jobs:
  tests:
    name: Tests check
    runs-on: ubuntu-latest
    steps:
      - name: Installation Go v1.21
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Start tests
        run: |
          go get github.com/golang/mock/gomock
          go install github.com/golang/mock/mockgen
          go get golang.org/x/tools/go/packages
          make mod
          make mock
          make tests

  linter:
    name: Linter check
    runs-on: ubuntu-latest
    steps:
      - name: Installation Go v1.21
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
          $(go env GOPATH)/bin/golangci-lint run --timeout=5m

  build:
    name: Run Build
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    needs: [ linter, tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Shutdown process
        run: make down
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push authorization
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/auth/Dockerfile
          platforms: linux/amd64
          push: true
          tags: 100ma/umlaut-auth:latest
      - name: Build and push feed
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/feed/Dockerfile
          platforms: linux/amd64
          push: true
          tags: 100ma/umlaut-feed:latest
      - name: Build and push admin
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/admin/Dockerfile
          platforms: linux/amd64
          push: true
          tags: 100ma/umlaut-admin:latest
      - name: Build and push app
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/app/Dockerfile
          platforms: linux/amd64
          push: true
          tags: 100ma/umlaut-app:latest
